version: "3.9"

services:
  api_express:
    container_name: api_express
    image: node:16
    build: .
    ports: 
      - 3000:3000
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    ports:
      - 5431:5432
    environment:
      - POSTGRES_USER=guilherme_linux
      - POSTGRES_PASSWORD=2003
      - POSTGRES_DB=products_management       
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  db_teste:
    container_name: db_teste
    image: postgres:12
    ports:
      - 5430:5432
    environment:
      - POSTGRES_USER=guilherme_linux
      - POSTGRES_PASSWORD=2003
      - POSTGRES_DB=tests_products       
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql